CREATE ROLE tn_owner LOGIN PASSWORD 'owner_pass' CREATEDB;
CREATE ROLE tn_app LOGIN PASSWORD 'app_pass' NOSUPERUSER NOBYPASSRLS;
ALTER DATABASE tunegocio OWNER TO tn_owner;
ALTER SCHEMA public OWNER TO tn_owner;
GRANT CONNECT ON DATABASE tunegocio TO tn_app;
GRANT USAGE ON SCHEMA public TO tn_app;
ALTER DEFAULT PRIVILEGES FOR ROLE tn_owner IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO tn_app;
ALTER DEFAULT PRIVILEGES FOR ROLE tn_owner IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO tn_app;